using AutoMapper;
using Newtonsoft.Json;
using StoreAPI.Dtos.CustomerDtos;
using StoreAPI.Models.User;

namespace StoreAPI.Data.Context
{
    public class DataSeeder
    {
        private readonly string _path = @"C:\Users\sva\Downloads\sample_user.json";

        private readonly ApplicationDbContext _db;

        private readonly IMapper _mapper;

        public DataSeeder(ApplicationDbContext db, IMapper mapper)
        {
            _db = db;
            _mapper = mapper;
        }

        public void Seed()
        {
            if (!_db.Customers.Any())
            {
                using (StreamReader r = new StreamReader(Path.GetFullPath(_path)))
                {
                    string json = r.ReadToEnd();

                    var users = JsonConvert.DeserializeObject<UsersSerializeDto>(json);

                    for (int i = 0; i < users.Users.Count; i++)
                    {
                        var user = users.Users[i];

                        var customer = _mapper.Map<Customer>(user);
                        var phoneNumbers = _mapper.Map<List<PhoneNumber>>(user.PhoneNumbers);

                        customer.Id = 0; //remove id from the object originated to json file, the id is autogenerated

                        _db.Customers.Add(customer);

                        _db.SaveChanges();
                    }
                }
            }
        }
    }
}
