using AutoMapper;
using Newtonsoft.Json;
using StoreAPI.Dtos;
using StoreAPI.Models.User;

namespace StoreAPI.Data
{
    public class DataSeeder
    {
        private readonly string _path = @"C:\Users\vasil\Downloads\sample_user.json";

        private readonly ApplicationDbContext _db;

        private readonly IMapper _mapper;

        public DataSeeder(ApplicationDbContext db, IMapper mapper)
        {
            _db = db;
            _mapper = mapper;
        }

        public void Seed()
        {
            if (!this._db.Customers.Any())
            {
                using (StreamReader r = new StreamReader(Path.GetFullPath(this._path)))
                {
                    string json = r.ReadToEnd();

                    var users = JsonConvert.DeserializeObject<UsersSerializeDto>(json);

                    for(int i = 0; i < users.Users.Count; i++)
                    {
                        var user = users.Users[i];

                        var customer = this._mapper.Map<Customer>(user);
                        var phoneNumbers = this._mapper.Map<List<PhoneNumber>>(user.PhoneNumbers);

                        customer.Id = 0; //remove id from the object originated to json file, the id is autogenerated

                        this._db.Customers.Add(customer);

                        this._db.SaveChanges();
                    }
                }
            }
        }
    }
}
